# Generated by Django 5.1 on 2024-10-09 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='license_key',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='license',
            name='created_at',
        ),
        migrations.AddField(
            model_name='license',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='LicenseValidation',
        ),
    ]
